### PR TITLE
Adding value pair series

### PR DESCRIPTION
**Pull request by KeilainMan**
One can add multiple value pair series, e.g. to show original points of a linear regression. So called "value pair series" can be removed or cleared for further usage.

### CODE REVIEW

**Comment by KeilainMan** [comment]
Hi. I used your nice addon for one of my projects and thought it would be nice to add some functionality that I was searching for in my project. Maybe you will consider my addition.
It's my first time contributing to another ones project, I hope I followed the right process haha. 
I tried to follow your coding practices.

**Comment by LD2Studio** [comment]
Hi, I'm glad you like this plugin.

I'm also new to PR. I'll take a look at your code over the next few days, and keep you posted.

**Comment by LD2Studio** [comment]
I've been looking at the new feature that displays points. One question: how do you add new points to a chart for which you've just deleted the pairs series with `clear_value_pair_series()`?
In my implementation, I have `add_point()` and `add_points()` functions which allow me to add new values to an existing plot.
It's useful to have this function, otherwise you can't update a curve created with `add_value_pairs_series()`.

It's a detail, but I suggest a shorter name like `add_scatter()` instead of `add_value_pairs_series()`; see  [Matplotlib](https://matplotlib.org/stable/plot_types/basic/scatter_plot.html) which served as the basis for my implementation of this addon.

Otherwise, thank you for sharing your experience with this plugin, which I hope will be useful to the community.

**Comment by KeilainMan** [comment]
Thanks for your thoughts. While implementing the changes I realized, that I mainly copied your code and changed some names. 
I then realized, that everything is already there and one could just implement a scatter flag to `add_curve()` and changing plot_2ds  draw function to draw circles instead of a polyline when the scatter flag is `true`. This would be like 5 lines of code :D 
Please tell me if you would like this addition or if a seperated plotting system would be prefered. :)

**Comment by LD2Studio** [comment]
Use `add_curve()` with a flag is a good solution; the simplest is always the best.

**Comment by KeilainMan** [comment]
Okay, I now changed everything to using a scatter plot flag. I dont know why I didn't realize sooner :D 
Thanks for your understanding. I think it could be a fine addition to your addon :)

**Comment by LD2Studio** [comment]
That's fine by me. I'm merging with the master branch
Thanks again
Note : I think I'll add this scatter option in the plugin for Godot 4 (https://github.com/LD2Studio/godot4-graph2d)

**Pull request merged**
